# temporary manual configuration, until everything is packaged.
# We need pinocchio and example-robot-data, as do crocoddyl, so we can use its image
# We care only about python 3, so we test only on 20.04


.pinocchio-tutorials: &pinocchio-tutorials
  retry:
    max: 2
    when: runner_system_failure
  except:
    - gh-pages
  script:
    - python -m unittest

pinocchio-tutorials-20.04:
  <<: *pinocchio-tutorials
  image: memmos.laas.fr:5000/loco-3d/crocoddyl/py-crocoddyl:20.04

format:
  image: gepetto/linters
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - test -f /builds/setup.cfg || ln -s /root/setup.cfg /builds
    - test -f /builds/.clang-format || ln -s /root/.clang-format /builds
  script:
    - flake8 utils examples tp2
    - nbqa flake8 2_geometry_3d.ipynb
    - yapf -dr utils examples tp2
    - nbqa yapf -ri 2_geometry_3d.ipynb
    - git diff --exit-code
